### ISSUE TITLE
ModuleNotFoundError: No module named 'flask'

### ISSUE THREAD

**Issue by okesten** [sagigvili/python-react-socket#1]
i tried every python version, still getting this error.
which version includes it?

**Comment by sagigvili** [comment]
That's my python version and pip list, pip install Flask has installed flask for me

Python 3.9.13
pip list
Package            Version
------------------ ----------
async-generator    1.10
attrs              22.2.0
autopep8           1.6.0
certifi            2022.12.7
cffi               1.15.1
click              8.1.3
colorama           0.4.6
exceptiongroup     1.1.0
**Flask              2.2.3**
Flask-Cors         3.0.10
flask-sock         0.6.0
h11                0.14.0
idna               3.4
importlib-metadata 6.0.0
itsdangerous       2.1.2
Jinja2             3.1.2
MarkupSafe         2.1.2
outcome            1.2.0
pycodestyle        2.8.0
pycparser          2.21
PySocks            1.7.1
selenium           4.7.2
simple-websocket   0.9.0
six                1.16.0
sniffio            1.3.0
sortedcontainers   2.4.0
toml               0.10.2
trio               0.22.0
trio-websocket     0.9.2
urllib3            1.26.13
Werkzeug           2.2.3
wsproto            1.2.0
youtube-dl         2021.12.17
zipp               3.15.0

**Comment by okesten** [comment]
how did you get this python version?
iapp251> ls -lh /usr/intel/pkgs/python3/
total 44K
drwxr-xr-x  7 usrintel       950 4.0K Nov 11 02:21 3.10.8
drwxr-xr-x 11 usrintel       950 4.0K Jan 12 00:30 3.11.1
drwxr-xr-x  7 usrintel usrintelg 4.0K Jan 10  2018 3.6.3
drwxr-xr-x  9 usrintel ctadmin   4.0K Sep  6  2022 3.6.3-gcc.640
lrwxrwxrwx  1 usrintel usrintelg    5 Nov  9  2018 3.6.3a -> 3.6.3
drwxr-xr-x  7 usrintel usrintelg 4.0K Jul 12  2019 3.7.4
drwxr-x---  4 usrintel usrintelg 4.0K Sep  3  2020 3.7.4.20191022
drwxr-x---  7 usrintel usrintelg 4.0K Jul 12  2019 3.7.4.20200205
drwxr-xr-x  7 usrintel ctadmin   4.0K Mar 26  2020 3.8.2
drwxr-xr-x  7 usrintel usrintelg 4.0K Aug 25  2021 3.9.6
-rw-r--r--  1 usrintel usrintelg  416 Sep  1  2020 dates
-rw-r--r--  1 usrintel ctadmin   1.1K Jan 13 17:14 versions
